In [1]:
import pandas as pd

df = pd.read_csv('Ride_Booking_Data.csv')

In [2]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,AvgVTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Reason for cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating
0,11/5/2026,15:05:51,CNR4188282,Success,CUST83407,Prime SUV,Wilson Garden,Hoodi,7.3,27.6,No,NaN,No,NaN,No,NaN,355.67,18.0,4.8,4.7
1,30/5/2026,11:23:36,CNR8458488,Pending,CUST98078,Bike,Shivajinagar,HSR Layout,NaN,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,NaN,NaN
2,23/5/2026,14:37:56,CNR2517038,Cancelled by Driver,CUST42762,Bike,Banashankari,HSR Layout,NaN,NaN,No,NaN,Yes,Personal & Car related issues,No,NaN,NaN,NaN,NaN,NaN
3,18/5/2026,1:31:03,CNR6459870,Cancelled by Customer,CUST86142,Prime SUV,MG Road,Peenya,NaN,NaN,Yes,Change of plans,No,NaN,No,NaN,NaN,NaN,NaN,NaN
4,4/5/2026,19:37:24,CNR2788393,Success,CUST43885,eBike,Cunningham Road,Sahakar Nagar,4.5,32.1,No,NaN,No,NaN,No,NaN,308.48,6.6,4.0,4.3

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               100000 non-null  str
 1   Time                               100000 non-null  str
 2   Booking ID                         100000 non-null  str
 3   Booking Status                     100000 non-null  str
 4   Customer ID                        100000 non-null  str
 5   Vehicle Type                       100000 non-null  str
 6   Pickup Location                    100000 non-null  str
 7   Drop Location                      100000 non-null  str
 8   AvgVTAT                            62000 non-null   float64
 9   Avg CTAT                           62000 non-null   float64
 10  Cancelled Rides by Customer        100000 non-null  str
 11  Reason for cancelling by Customer  7000 non-null    str
 12  Cancelled Rides by Driver          100000 non-null  str
 13  Reason for cancelling by Driver    18000 non-null   str
 14  Incomplete Rides                   100000 non-null  str
 15  Incomplete Rides Reason            5000 non-null    str
 16  Booking Value                      62000 non-null   float64
 17  Ride Distance                      62000 non-null   float64
 18  Driver Ratings                     62000 non-null   float64
 19  Customer Rating                    62000 non-null   float64
dtypes: float64(6), str(14)
memory usage: 15.3 MB

In [4]:
# Summary statistics using .describe()
df.describe(include='all')

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,AvgVTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Reason for cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,100000,100000,100000,100000,100000,100000,100000,100000,62000.000000,62000.000000,100000,7000,100000,18000,100000,5000,62000.000000,62000.000000,62000.000000,62000.000000
unique,31,52842,99478,5,60377,7,50,50,NaN,NaN,2,5,2,4,2,3,NaN,NaN,NaN,NaN
top,10/5/2026,16:55:18,CNR9151228,Success,CUST62437,eBike,Banashankari,Nagawara,NaN,NaN,No,Driver is not moving towards pickup location,No,The customer was coughing/sick,No,Other Issue,NaN,NaN,NaN,NaN
freq,7543,11,2,62000,8,14526,2116,2134,NaN,NaN,93000,1606,82000,4552,95000,1701,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.992095,34.932942,NaN,NaN,NaN,NaN,NaN,NaN,510.733626,18.261066,4.249394,4.252773
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.889683,14.418537,NaN,NaN,NaN,NaN,NaN,NaN,363.366867,9.641512,0.435433,0.434092
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,1.500000,3.500000,3.500000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,22.400000,NaN,NaN,NaN,NaN,NaN,NaN,258.927500,9.900000,3.900000,3.900000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,34.900000,NaN,NaN,NaN,NaN,NaN,NaN,427.870000,18.300000,4.300000,4.300000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.500000,47.400000,NaN,NaN,NaN,NaN,NaN,NaN,662.097500,26.600000,4.600000,4.600000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,3457.160000,35.000000,5.000000,5.000000

In [5]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
AvgVTAT                              38000
Avg CTAT                             38000
Cancelled Rides by Customer              0
Reason for cancelling by Customer    93000
Cancelled Rides by Driver                0
Reason for cancelling by Driver      82000
Incomplete Rides                         0
Incomplete Rides Reason              95000
Booking Value                        38000
Ride Distance                        38000
Driver Ratings                       38000
Customer Rating                      38000
dtype: int64

In [6]:
# 1. AvgVTAT

df['AvgVTAT'] = df['AvgVTAT'].fillna(df['AvgVTAT'].median())

# 2. Avg CTAT

df['Avg CTAT'] = df['Avg CTAT'].fillna(df['Avg CTAT'].median())

# 3. Reason for cancelling by Customer

df['Reason for cancelling by Customer'] = (
    df['Reason for cancelling by Customer']
    .fillna('Not Applicable')
)

# 4. Reason for cancelling by Driver

df['Reason for cancelling by Driver'] = (
    df['Reason for cancelling by Driver']
    .fillna('Not Applicable')
)

# 5. Incomplete Rides Reason

df['Incomplete Rides Reason'] = (
    df['Incomplete Rides Reason']
    .fillna('Not Applicable')
)

# 6. Booking Value

df['Booking Value'] = (
    df['Booking Value']
    .fillna(df['Booking Value'].median())
)

# 7. Ride Distance

df['Ride Distance'] = (
    df['Ride Distance']
    .fillna(df['Ride Distance'].median())
)

# 8. Driver Ratings

df['Driver Ratings'] = (
    df['Driver Ratings']
    .fillna(df['Driver Ratings'].mean())
)

# 9. Customer Rating

df['Customer Rating'] = (
    df['Customer Rating']
    .fillna(df['Customer Rating'].mean())
)

In [7]:
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
AvgVTAT                              0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Reason for cancelling by Driver      0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
dtype: int64

In [8]:
# snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [9]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avgvtat',
       'avg_ctat', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'reason_for_cancelling_by_driver', 'incomplete_rides',
       'incomplete_rides_reason', 'booking_value', 'ride_distance',
       'driver_ratings', 'customer_rating'],
      dtype='str')

In [13]:
import numpy as np
# Payment methods
payment_methods = [
    "Cash",
    "UPI",
    "Credit Card",
    "Debit Card",
    "Wallet"
]

# Add new column
df["payment_method"] = np.random.choice(
    payment_methods,
    size=len(df),
    p=[0.25, 0.45, 0.12, 0.10, 0.08]
)

In [14]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avgvtat',
       'avg_ctat', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'reason_for_cancelling_by_driver', 'incomplete_rides',
       'incomplete_rides_reason', 'booking_value', 'ride_distance',
       'driver_ratings', 'customer_rating', 'payment_method'],
      dtype='str')

In [15]:
!pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\ashmita karmakar\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\ashmita karmakar\appdata\roaming\python\python313\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\ashmita karmakar\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ashmita karmakar\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "rini07" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "Sales_analysis"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "ride_data"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'ride_data' in database 'Sales_analysis'.